// TODO: Replace these symbols with their corresponding commands so that the parser doesn't crash

let greek = {
  α: /\\alpha/g,
  β: /\\beta/g,
  γ: /\\gamma/g,
  Γ: /\\Gamma/g,
  δ: /\\delta/g,
  Δ: /\\Delta/g,
  "∆": /\\Delta/g,
  ϵ: /\\epsilon/g,
  ε: /\\varepsilon/g,
  ζ: /\\zeta/g,
  η: /\\eta/g,
  θ: /\\theta/g,
  ϑ: /\\vartheta/g,
  Θ: /\\Theta/g,
  κ: /\\kappa/g,
  λ: /\\lambda/g,
  Λ: /\\Lambda/g,
  μ: /\\mu/g,
  µ: /\\mu/g,
  ν: /\\nu/g,
  ξ: /\\xi/g,
  Ξ: /\\Xi/g,
  π: /\\pi/g,
  Π: /\\Pi/g,
  ϖ: /\\varpi/g,
  ρ: /\\rho/g,
  ϱ: /\\varrho/g,
  σ: /\\sigma/g,
  Σ: /\\Sigma/g,
  ς: /\\varsigma/g,
  τ: /\\tau/g,
  υ: /\\upsilon/g,
  Υ: /\\Upsilon/g,
  φ: /\\phi/g,
  Φ: /\\Phi/g,
  ϕ: /\\varphi/g,
  χ: /\\chi/g,
  ψ: /\\psi/g,
  Ψ: /\\Psi/g,
  ω: /\\omega/g,
  Ω: /\\Omega/g,
}

let other = {
  "°": /\\degree/g,
  Å: /\\AA/g,
  "∂": /\\partial/g,
  "∞": /\\infinity/g,
  "•": /\\cdot/g,
  "⁄": /\\over/g
}
